-- Custom SQL migration file, put your code below! --
-- SKIPPED: pg_search extension is deprecated on Neon Free tier and no longer allowed.
-- Full-text search indexes relying on this extension have been disabled.
