-- Custom SQL migration file, put your code below! --
-- SKIPPED: BM25 indexes require pg_search extension which is deprecated on Neon Free tier.
-- All CREATE INDEX statements using bm25 have been removed to ensure migration compatibility.
